// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiZCkdhVWp-Sr_th0-vM7k1xRpdPamZKU',
    appId: '1:549979493097:web:b4bd5c232075cdd3ae5678',
    messagingSenderId: '549979493097',
    projectId: 'upray-f90d5',
    authDomain: 'upray-f90d5.firebaseapp.com',
    storageBucket: 'upray-f90d5.appspot.com',
    measurementId: 'G-P8FEL8WYZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJpW1W9tm9N-d46hhV05f1_j85oOqRx_o',
    appId: '1:549979493097:android:c3a2d1e8ff220b95ae5678',
    messagingSenderId: '549979493097',
    projectId: 'upray-f90d5',
    storageBucket: 'upray-f90d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9LFhv95VAgb3bLLm6Bu7txXx2B44z32o',
    appId: '1:549979493097:ios:4b89d9ad35e39e55ae5678',
    messagingSenderId: '549979493097',
    projectId: 'upray-f90d5',
    storageBucket: 'upray-f90d5.appspot.com',
    iosClientId: '549979493097-kra0csmfjjv4lggdq03d43tdig72cohe.apps.googleusercontent.com',
    iosBundleId: 'com.ugroup.upray',
  );
}
